version: '3'
services:
  db:
    image: postgres
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bidder_db
  web:
    image: nikitasmall/bidder:latest
    command: ["./waiter.sh", "db:5432", "--", "/go/bin/bidder"]
    depends_on:
      - db
    ports:
      - "3000:8080"
    environment:
      - GIN_MODE=release
      - POSTGRES=postgres://root:toor@db:5432/bidder_db?sslmode=disable
