version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bidder
  web:
    build: .
    command: ["./waiter.sh", "db:5432", "--", "/go/bin/bidder"]
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - POSTGRES=postgres://root:toor@db:5432/bidder?sslmode=disable
